# Generated by Django 2.1.5 on 2019-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='care_of',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
