# Generated by Django 2.1.5 on 2019-02-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=30)),
                ('dr_email', models.CharField(max_length=40, null=True)),
                ('dr_mobile', models.CharField(max_length=25)),
            ],
        ),
    ]
