# Generated by Django 2.1.5 on 2019-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=40)),
                ('test_unit', models.CharField(max_length=10, null=True)),
                ('test_range', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
